title: Debate Dragons
logo: "/assets/images/batey.webp"
description: An introduction to debate and our debate club!
theme: just-the-docs

url: https://just-the-docs.github.io

#aux_links:
  #Template Repository: https://github.com/just-the-docs/just-the-docs-template
