title: Debate Dragons
logo: "assets/images/tonguebatey.png"
description: An introduction to debate and our debate club!
theme: just-the-docs

url: https://just-the-docs.github.io

head_scripts: |
  <link rel="icon" type="image/png" href="/assets/favicon/favicon-32x32.png">

#aux_links:
  #Template Repository: https://github.com/just-the-docs/just-the-docs-template
